version: "3"
services:
 
  mysql:
    image: mysql:5.7
    #restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=true --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mysite

  web:
    container_name: web
    restart: always
    build: .

    environment:
      - TZ=Asia/Shanghai

    volumes:
      - .:/web
    command:
      - /bin/bash
      - -c
      - |
        gunicorn -c site_tset/gunicorn-config.py site_tset.wsgi
#        gunicorn site_tset.wsgi -b 0.0.0.0:8000
#        python manage.py runserver 0.0.0.0:8000
#        python manage.py makemigrations
#        python manage.py migrate


    links:
      - "mysql:mysql"

  nginx:
    image: nginx:latest
#    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/root/static

    links:
      - web:web

